"""add_feature_suggestions_table

Revision ID: 1bdbc5757031
Revises: fe2bfa1737ee
Create Date: 2026-06-23 12:36:53.909011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bdbc5757031'
down_revision: Union[str, Sequence[str], None] = 'fe2bfa1737ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_suggestions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.Enum('FEATURE', 'UI', 'BUGFIX', 'OPTIMIZATION', 'SECURITY', name='suggestioncategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('effort', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='suggestioneffort'), nullable=False),
    sa.Column('files', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_REVIEW', 'IMPLEMENTED', 'DISMISSED', name='suggestionstatus'), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('ollama_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('implemented_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feature_suggestions_category', 'feature_suggestions', ['category'], unique=False)
    op.create_index('ix_feature_suggestions_created_at', 'feature_suggestions', ['created_at'], unique=False)
    op.create_index('ix_feature_suggestions_status', 'feature_suggestions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feature_suggestions_status', table_name='feature_suggestions')
    op.drop_index('ix_feature_suggestions_created_at', table_name='feature_suggestions')
    op.drop_index('ix_feature_suggestions_category', table_name='feature_suggestions')
    op.drop_table('feature_suggestions')
    # ### end Alembic commands ###
