"""add setup_wizard_complete to users

Revision ID: 519a3465ed1e
Revises: 048b348f3008
Create Date: 2026-06-14 16:48:18.005053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '519a3465ed1e'
down_revision: Union[str, Sequence[str], None] = '048b348f3008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('setup_wizard_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'setup_wizard_complete')
    # ### end Alembic commands ###
