"""add_job_progress_fields

Revision ID: 96411cf92a3b
Revises: 1bdbc5757031
Create Date: 2026-06-24 12:47:39.388362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96411cf92a3b'
down_revision: Union[str, Sequence[str], None] = '1bdbc5757031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('progress_stage', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('progress_percent', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('progress_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'progress_message')
    op.drop_column('jobs', 'progress_percent')
    op.drop_column('jobs', 'progress_stage')
    # ### end Alembic commands ###
