"""initial_schema

Revision ID: f319c47658ec
Revises:
Create Date: 2026-08-13 23:53:58.614863

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f319c47658ec"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_suggestions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column(
            "category",
            sa.Enum("FEATURE", "UI", "BUGFIX", "OPTIMIZATION", "SECURITY", name="suggestioncategory"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("effort", sa.Enum("LOW", "MEDIUM", "HIGH", name="suggestioneffort"), nullable=False),
        sa.Column("files", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.Enum("NEW", "IN_REVIEW", "IMPLEMENTED", "DISMISSED", name="suggestionstatus"), nullable=False
        ),
        sa.Column("votes", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("ollama_model", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("implemented_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_feature_suggestions_category", "feature_suggestions", ["category"], unique=False)
    op.create_index("ix_feature_suggestions_created_at", "feature_suggestions", ["created_at"], unique=False)
    op.create_index("ix_feature_suggestions_status", "feature_suggestions", ["status"], unique=False)
    op.create_table(
        "invite_keys",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.Column("used_count", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invite_keys_code"), "invite_keys", ["code"], unique=True)
    op.create_table(
        "oauth_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("code_verifier", sa.Text(), nullable=True),
        sa.Column("redirect_uri", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_oauth_states_created_at"), "oauth_states", ["created_at"], unique=False)
    op.create_index(op.f("ix_oauth_states_id"), "oauth_states", ["id"], unique=False)
    op.create_index(op.f("ix_oauth_states_state"), "oauth_states", ["state"], unique=True)
    op.create_table(
        "rate_limit_entries",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("ip", sa.String(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rate_limit_entries_ip"), "rate_limit_entries", ["ip"], unique=False)
    op.create_index("ix_rate_limit_ip_expires_at", "rate_limit_entries", ["ip", "expires_at"], unique=False)
    op.create_table(
        "tenants",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("domain", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("max_users", sa.Integer(), nullable=True),
        sa.Column("max_storage_gb", sa.Integer(), nullable=True),
        sa.Column("features", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    op.create_table(
        "webhook_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("payload", sa.Text(), nullable=True),
        sa.Column("processed", sa.Boolean(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "event_id", name="uq_webhook_event_source_id"),
    )
    op.create_table(
        "whop_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("whop_event_id", sa.String(), nullable=True),
        sa.Column("payload", sa.Text(), nullable=True),
        sa.Column("processed", sa.Boolean(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("whop_event_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("tenant_id", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("google_id", sa.String(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("password_salt", sa.String(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("subscription_tier", sa.Enum("FREE", "PRO", "ENTERPRISE", name="subscriptiontier"), nullable=True),
        sa.Column("credits_used_month", sa.Integer(), nullable=True),
        sa.Column("credits_limit_month", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("setup_wizard_complete", sa.Boolean(), nullable=True),
        sa.Column("stripe_customer_id", sa.String(), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(), nullable=True),
        sa.Column("whop_customer_id", sa.String(), nullable=True),
        sa.Column("whop_license_key", sa.String(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=True),
        sa.Column("verification_token", sa.String(), nullable=True),
        sa.Column("reset_token", sa.String(), nullable=True),
        sa.Column("reset_token_expires", sa.DateTime(), nullable=True),
        sa.Column("trial_ends_at", sa.DateTime(), nullable=True),
        sa.Column("dunning_count", sa.Integer(), nullable=True),
        sa.Column("last_dunning_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_google_id"), "users", ["google_id"], unique=False)
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_table(
        "account_groups",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_account_groups_user_id"), "account_groups", ["user_id"], unique=False)
    op.create_table(
        "api_keys",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("key_hash", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
    )
    op.create_index(op.f("ix_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("filename", sa.String(), nullable=True),
        sa.Column("video_path", sa.String(), nullable=True),
        sa.Column("endscreen_path", sa.String(), nullable=True),
        sa.Column("cta_text", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("drive_url", sa.String(), nullable=True),
        sa.Column("target_language", sa.String(), nullable=True),
        sa.Column("aspect_ratio", sa.String(), nullable=True),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("analysis_json", sa.Text(), nullable=True),
        sa.Column("clips_json", sa.Text(), nullable=True),
        sa.Column("thinking_json", sa.Text(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("timing_transcription", sa.Float(), nullable=True),
        sa.Column("timing_analysis", sa.Float(), nullable=True),
        sa.Column("timing_cutting", sa.Float(), nullable=True),
        sa.Column("timing_total", sa.Float(), nullable=True),
        sa.Column("progress_stage", sa.String(), nullable=True),
        sa.Column("progress_percent", sa.Integer(), nullable=True),
        sa.Column("progress_message", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jobs_status"), "jobs", ["status"], unique=False)
    op.create_index("ix_jobs_user_created", "jobs", ["user_id", "created_at"], unique=False)
    op.create_index(op.f("ix_jobs_user_id"), "jobs", ["user_id"], unique=False)
    op.create_index("ix_jobs_user_status", "jobs", ["user_id", "status"], unique=False)
    op.create_table(
        "personas",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("avatar_path", sa.String(), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("brand_colors", sa.Text(), nullable=True),
        sa.Column("voice_description", sa.Text(), nullable=True),
        sa.Column("target_audience", sa.Text(), nullable=True),
        sa.Column("content_pillars", sa.Text(), nullable=True),
        sa.Column("tone", sa.String(), nullable=True),
        sa.Column("platform_settings", sa.Text(), nullable=True),
        sa.Column("auto_approve", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_personas_user_id"), "personas", ["user_id"], unique=False)
    op.create_table(
        "publish_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("account_name", sa.String(length=255), nullable=True),
        sa.Column("clip_filename", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_publish_history_id"), "publish_history", ["id"], unique=False)
    op.create_index(op.f("ix_publish_history_platform"), "publish_history", ["platform"], unique=False)
    op.create_index("ix_publish_history_user_created", "publish_history", ["user_id", "created_at"], unique=False)
    op.create_index(op.f("ix_publish_history_user_id"), "publish_history", ["user_id"], unique=False)
    op.create_table(
        "social_accounts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("account_name", sa.String(), nullable=False),
        sa.Column("auth_mode", sa.String(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("oauth_refresh_token_enc", sa.Text(), nullable=True),
        sa.Column("instagram_user_id", sa.String(), nullable=True),
        sa.Column("instagram_access_token_enc", sa.Text(), nullable=True),
        sa.Column("tiktok_open_id", sa.String(), nullable=True),
        sa.Column("tiktok_refresh_token_enc", sa.Text(), nullable=True),
        sa.Column("tiktok_access_token_enc", sa.Text(), nullable=True),
        sa.Column("twitter_user_id", sa.String(), nullable=True),
        sa.Column("twitter_access_token_enc", sa.Text(), nullable=True),
        sa.Column("facebook_page_id", sa.String(), nullable=True),
        sa.Column("facebook_access_token_enc", sa.Text(), nullable=True),
        sa.Column("linkedin_user_id", sa.String(), nullable=True),
        sa.Column("linkedin_access_token_enc", sa.Text(), nullable=True),
        sa.Column("youtube_privacy_status", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_social_accounts_user_active", "social_accounts", ["user_id", "is_active"], unique=False)
    op.create_index(op.f("ix_social_accounts_user_id"), "social_accounts", ["user_id"], unique=False)
    op.create_table(
        "templates",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("niche", sa.String(), nullable=True),
        sa.Column("caption_style", sa.String(), nullable=True),
        sa.Column("platform", sa.String(), nullable=True),
        sa.Column("duration", sa.String(), nullable=True),
        sa.Column("broll_mode", sa.String(), nullable=True),
        sa.Column("language", sa.String(), nullable=True),
        sa.Column("aspect_ratio", sa.String(), nullable=True),
        sa.Column("is_default", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_templates_user_id"), "templates", ["user_id"], unique=False)
    op.create_table(
        "whop_licenses",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("license_key", sa.String(), nullable=False),
        sa.Column("product_id", sa.String(), nullable=False),
        sa.Column("tier", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("whop_purchase_id", sa.String(), nullable=True),
        sa.Column("whop_customer_id", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_whop_licenses_license_key"), "whop_licenses", ["license_key"], unique=True)
    op.create_index(op.f("ix_whop_licenses_user_id"), "whop_licenses", ["user_id"], unique=False)
    op.create_table(
        "campaigns",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("platforms", sa.Text(), nullable=True),
        sa.Column("persona_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("daily_post_count", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_campaigns_user_id"), "campaigns", ["user_id"], unique=False)
    op.create_table(
        "group_accounts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("group_id", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["social_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["account_groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "posts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("persona_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=True),
        sa.Column("campaign_id", sa.String(), nullable=True),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("media_path", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(), nullable=True),
        sa.Column("posted_at", sa.DateTime(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("source_transcript", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_posts_campaign_id"), "posts", ["campaign_id"], unique=False)
    op.create_index(op.f("ix_posts_persona_id"), "posts", ["persona_id"], unique=False)
    op.create_index(op.f("ix_posts_platform"), "posts", ["platform"], unique=False)
    op.create_index(op.f("ix_posts_status"), "posts", ["status"], unique=False)
    op.create_index("ix_posts_user_created", "posts", ["user_id", "created_at"], unique=False)
    op.create_index(op.f("ix_posts_user_id"), "posts", ["user_id"], unique=False)
    op.create_index("ix_posts_user_status", "posts", ["user_id", "status"], unique=False)
    op.create_table(
        "schedules",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("persona_id", sa.String(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=True),
        sa.Column("time", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["persona_id"],
            ["personas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_schedules_persona_id"), "schedules", ["persona_id"], unique=False)
    op.create_table(
        "thumbnails",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("clip_index", sa.Integer(), nullable=False),
        sa.Column("variant_name", sa.String(), nullable=True),
        sa.Column("image_path", sa.String(), nullable=True),
        sa.Column("title_overlay", sa.String(), nullable=True),
        sa.Column("layout", sa.String(), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("is_winner", sa.Boolean(), nullable=True),
        sa.Column("impressions", sa.Integer(), nullable=True),
        sa.Column("clicks", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_thumbnails_job_id"), "thumbnails", ["job_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_thumbnails_job_id"), table_name="thumbnails")
    op.drop_table("thumbnails")
    op.drop_index(op.f("ix_schedules_persona_id"), table_name="schedules")
    op.drop_table("schedules")
    op.drop_index("ix_posts_user_status", table_name="posts")
    op.drop_index(op.f("ix_posts_user_id"), table_name="posts")
    op.drop_index("ix_posts_user_created", table_name="posts")
    op.drop_index(op.f("ix_posts_status"), table_name="posts")
    op.drop_index(op.f("ix_posts_platform"), table_name="posts")
    op.drop_index(op.f("ix_posts_persona_id"), table_name="posts")
    op.drop_index(op.f("ix_posts_campaign_id"), table_name="posts")
    op.drop_table("posts")
    op.drop_table("group_accounts")
    op.drop_index(op.f("ix_campaigns_user_id"), table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_index(op.f("ix_whop_licenses_user_id"), table_name="whop_licenses")
    op.drop_index(op.f("ix_whop_licenses_license_key"), table_name="whop_licenses")
    op.drop_table("whop_licenses")
    op.drop_index(op.f("ix_templates_user_id"), table_name="templates")
    op.drop_table("templates")
    op.drop_index(op.f("ix_social_accounts_user_id"), table_name="social_accounts")
    op.drop_index("ix_social_accounts_user_active", table_name="social_accounts")
    op.drop_table("social_accounts")
    op.drop_index(op.f("ix_publish_history_user_id"), table_name="publish_history")
    op.drop_index("ix_publish_history_user_created", table_name="publish_history")
    op.drop_index(op.f("ix_publish_history_platform"), table_name="publish_history")
    op.drop_index(op.f("ix_publish_history_id"), table_name="publish_history")
    op.drop_table("publish_history")
    op.drop_index(op.f("ix_personas_user_id"), table_name="personas")
    op.drop_table("personas")
    op.drop_index("ix_jobs_user_status", table_name="jobs")
    op.drop_index(op.f("ix_jobs_user_id"), table_name="jobs")
    op.drop_index("ix_jobs_user_created", table_name="jobs")
    op.drop_index(op.f("ix_jobs_status"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_api_keys_user_id"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_account_groups_user_id"), table_name="account_groups")
    op.drop_table("account_groups")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_index(op.f("ix_users_google_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("whop_events")
    op.drop_table("webhook_events")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_index("ix_rate_limit_ip_expires_at", table_name="rate_limit_entries")
    op.drop_index(op.f("ix_rate_limit_entries_ip"), table_name="rate_limit_entries")
    op.drop_table("rate_limit_entries")
    op.drop_index(op.f("ix_oauth_states_state"), table_name="oauth_states")
    op.drop_index(op.f("ix_oauth_states_id"), table_name="oauth_states")
    op.drop_index(op.f("ix_oauth_states_created_at"), table_name="oauth_states")
    op.drop_table("oauth_states")
    op.drop_index(op.f("ix_invite_keys_code"), table_name="invite_keys")
    op.drop_table("invite_keys")
    op.drop_index("ix_feature_suggestions_status", table_name="feature_suggestions")
    op.drop_index("ix_feature_suggestions_created_at", table_name="feature_suggestions")
    op.drop_index("ix_feature_suggestions_category", table_name="feature_suggestions")
    op.drop_table("feature_suggestions")
    # ### end Alembic commands ###
